---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "lockfile-only"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
